streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/site
         - user/themes/learn2
github:
    position: top                                   # top | bottom | off
    tree: https://github.com/userfrosting/learn/blob/develop/
    commits: https://github.com/userfrosting/learn/commits/develop/
